---
driver:
  name: vagrant
  customize:
    memory: 1024
  require_chef_omnibus: true

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-15.04
    run_list:
      - recipe[ubuntu::default]

suites:
  - name: default
    run_list:
      - recipe[testprep::curl]
      - recipe[aircover::default]
